Changed when environment takes effects
RS117/RLHD pull request #245
Opened 2022-03-08 16:37 UTC by Mark7625

With the old system if you was near another Environment and your camera angle was within that location sometimes it would change the Environment  based on where your camera was in, this change only changes once the player is within this range

https://i.imgur.com/ltHYzux.gif

2022-03-08 16:38 UTC, Mark7625 commented
Please feel free to discuss any reasons why it was based on the camera and not the player

2022-03-08 18:18 UTC, sosodev requested changes

2022-03-08 18:25 UTC, Mark7625 commented on src/main/java/rs117/hd/environments/EnvironmentManager.java
> +		WorldPoint camPosition = hdPlugin.getClient().getLocalPlayer().getWorldLocation();
Thanks I have made the required changes

2022-03-09 16:03 UTC, sosodev commented
It appears that this has some unintended effects. My house environment is different with the changes and that shouldn't be the case. 

![house-branch](https://user-images.githubusercontent.com/13486671/157480165-10516741-9016-456a-b492-1b42ccff4f30.png)
![house-before](https://user-images.githubusercontent.com/13486671/157480172-609e59e1-697e-4923-bc98-82f8f37fedda.png)

2022-03-09 16:11 UTC, sosodev commented
With nothing defined it should just use the defaults I believe

2022-05-06 19:18 UTC, closed without merging